In [1]:
import glob
import pandas as pd

In [3]:
# Merging csv files (without repeating header)
all_years_files = glob.glob("data/*.csv") 
df = pd.concat((pd.read_csv(f, header = 0) for f in all_years_files))
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,142,2019-02-01 15:35:02.0820,2019-02-01 15:37:24.1360,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29677,Subscriber,1963,1
1,223,2019-02-01 17:00:46.8900,2019-02-01 17:04:30.5500,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,26234,Subscriber,1992,2
2,106,2019-02-01 17:08:01.3260,2019-02-01 17:09:47.4400,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29588,Subscriber,1960,1
3,370,2019-02-01 17:09:31.2100,2019-02-01 17:15:41.6550,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,29250,Subscriber,1976,1
4,315,2019-02-01 17:19:53.2490,2019-02-01 17:25:09.1400,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,29586,Subscriber,1980,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36130,792,2019-05-31 23:51:00.1170,2019-06-01 00:04:12.4530,3186,Grove St PATH,40.719586,-74.043117,3214,Essex Light Rail,40.712774,-74.036486,26236,Customer,1991,1
36131,779,2019-05-31 23:51:22.7840,2019-06-01 00:04:22.3990,3186,Grove St PATH,40.719586,-74.043117,3214,Essex Light Rail,40.712774,-74.036486,29205,Customer,1991,2
36132,347,2019-05-31 23:55:38.3850,2019-06-01 00:01:26.2030,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26179,Subscriber,1989,2
36133,552,2019-05-31 23:56:11.9740,2019-06-01 00:05:24.8810,3192,Liberty Light Rail,40.711242,-74.055701,3277,Communipaw & Berry Lane,40.714358,-74.066611,29528,Subscriber,1992,1
36134,520,2019-05-31 23:56:25.0240,2019-06-01 00:05:05.4860,3192,Liberty Light Rail,40.711242,-74.055701,3277,Communipaw & Berry Lane,40.714358,-74.066611,29589,Subscriber,1984,2

In [5]:
# Export file as a CSV
df.to_csv("data/2019-citibike-tripsdata.csv")